# Generated by Django 4.0.6 on 2022-07-23 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinemania_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('user_gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Others', 'O')], max_length=15)),
                ('email_token', models.CharField(max_length=250)),
                ('avatar', models.ImageField(upload_to='')),
                ('is_verfied', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('release_date', models.DateField()),
                ('main_actors', models.TextField()),
                ('genre', models.TextField()),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='')),
                ('movie_trailer', models.CharField(max_length=250)),
                ('posted_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemania_app.createuser')),
            ],
        ),
    ]
