# Generated by Django 4.0.6 on 2022-07-23 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinemania_app', '0003_alter_contactus_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='createuser',
            name='id',
        ),
        migrations.AddField(
            model_name='createuser',
            name='user_uuid',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AddPost',
        ),
    ]
