# Generated by Django 4.0.6 on 2022-07-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemania_app', '0006_rename_user_addpost_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpost',
            name='movie_trailer',
            field=models.CharField(default='www.youtube.com', max_length=250),
        ),
    ]
