# Generated by Django 4.0.6 on 2022-07-31 08:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cinemania_app', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 8, 38, 32, 729961, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
